# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
# yaml-language-server: $schema=../../tools/schemas/jrtc-ctl.schema.json

name: FirstExample

app:
  - name: app1
    path: ${JRTC_PATH}/sample_apps/first_example/app1.so
    port: 3001
    type: c
    params:
      key: value

jbpf:
  device:
    - id: 1
      port: 8080

  codelet_set:
    - device: 1
      config: ${JRTC_PATH}/sample_apps/first_example/jbpf_codelets/data_generator/data_generator_codelet.yaml

    - device: 1
      config: ${JRTC_PATH}/sample_apps/first_example/jbpf_codelets/simple_input/codeletset.yaml
