/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_GENERATED_DATA_PB_H_INCLUDED
#define PB_GENERATED_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _example_msg_pb {
    uint32_t cnt;
} example_msg_pb;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define example_msg_pb_init_default              {0}
#define example_msg_pb_init_zero                 {0}

/* Field tags (for use in manual encoding/decoding) */
#define example_msg_pb_cnt_tag                   1

/* Struct field encoding specification for nanopb */
#define example_msg_pb_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   cnt,               1)
#define example_msg_pb_CALLBACK NULL
#define example_msg_pb_DEFAULT NULL

extern const pb_msgdesc_t example_msg_pb_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define example_msg_pb_fields &example_msg_pb_msg

/* Maximum encoded size of messages (where known) */
#define GENERATED_DATA_PB_H_MAX_SIZE             example_msg_pb_size
#define example_msg_pb_size                      6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
